Ray cluster started. Available resources: {'CPU': 12.0, 'object_store_memory': 4122133708.0, 'node:__internal_head__': 1.0, 'accelerator_type:G': 1.0, 'memory': 9618311988.0, 'GPU': 1.0, 'node:172.23.48.184': 1.0}
Waiting for actors to initialize and run one episode...
[36m(DataActor pid=6561)[0m (DataActor pid=6561) Initializing on CPU...
[36m(DataActor pid=6561)[0m (DataActor pid=6561) Setup complete.
[36m(LearnerActor pid=6566)[0m (Learner pid=6566) Initializing on GPU...
[36m(LearnerActor pid=6566)[0m (Learner pid=6566) Setup complete.
[36m(DataActor pid=6560)[0m (DataActor pid=6560) Initializing on CPU...[32m [repeated 5x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(DataActor pid=6560)[0m (DataActor pid=6560) Setup complete.[32m [repeated 5x across cluster][0m

Warmup phase...
  Buffer size: 999/1000
Warmup complete. Starting main training loop.
Episodes: 1100 | Avg Return: -1422.25 | Avg Loss: 402.8192 | Time: 75.17s
Episodes: 1200 | Avg Return: -1522.42 | Avg Loss: 402.6955 | Time: 53.93s
Episodes: 1300 | Avg Return: -1629.71 | Avg Loss: 402.6639 | Time: 54.36s
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/tokenize.py", line 396, in open
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/tokenize.py", line 365, in detect_encoding
    first = read_or_stop()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/tokenize.py", line 323, in read_or_stop
    return readline()
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 327, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 286, in main
    done_actor_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
  File "python/ray/_raylet.pyx", line 3480, in ray._raylet.CoreWorker.wait
  File "python/ray/includes/common.pxi", line 83, in ray._raylet.check_status
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x748004673f40>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 90, in teardown_atexit
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 218, in teardown
    self._router.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1096, in join
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
[0m
Exception ignored in atexit callback: <function shutdown at 0x748027c216c0>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 1987, in shutdown
    disconnect(_exiting_interpreter)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 2639, in disconnect
    worker.gcs_error_subscriber.close()
KeyboardInterrupt:
