Ray cluster started. Available resources: {'object_store_memory': 4174287667.0, 'accelerator_type:G': 1.0, 'node:172.23.48.184': 1.0, 'GPU': 1.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'memory': 9740004557.0}
Waiting for actors to initialize and run one episode...
[36m(LearnerActor pid=7258)[0m (Learner pid=7258) Initializing on GPU...
[36m(LearnerActor pid=7258)[0m (Learner pid=7258) Setup complete.
[36m(DataActor pid=7266)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::ReplayBufferActor.add()[39m (pid=7259, ip=172.23.48.184, actor_id=32300c93bcfc9e0ae856bcd701000000, repr=<train.ReplayBufferActor object at 0x78eff01ce650>)
[36m(DataActor pid=7266)[0m   File "/home/ryan/toy_mazero/train.py", line 45, in add
[36m(DataActor pid=7266)[0m     self.replay_buffer.add(item, priority)
[36m(DataActor pid=7266)[0m   File "/home/ryan/toy_mazero/utils/replay_buffer.py", line 125, in add
[36m(DataActor pid=7266)[0m     self.observations[self.pointer] = item.observation
[36m(DataActor pid=7266)[0m ValueError: could not broadcast input array from shape (3,18) into shape (18,)

Warmup phase...
  Buffer size: 0/1000
[36m(DataActor pid=7260)[0m [32m2025-06-29 15:57:11[0m | [36mDEBUG[0m | [36mUpdating parameters from learner.[0m
[36m(DataActor pid=7267)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::ReplayBufferActor.add()[39m (pid=7259, ip=172.23.48.184, actor_id=32300c93bcfc9e0ae856bcd701000000, repr=<train.ReplayBufferActor object at 0x78eff01ce650>)[32m [repeated 242x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(DataActor pid=7267)[0m   File "/home/ryan/toy_mazero/train.py", line 45, in add[32m [repeated 242x across cluster][0m
[36m(DataActor pid=7267)[0m     self.replay_buffer.add(item, priority)[32m [repeated 242x across cluster][0m
[36m(DataActor pid=7267)[0m   File "/home/ryan/toy_mazero/utils/replay_buffer.py", line 125, in add[32m [repeated 242x across cluster][0m
[36m(DataActor pid=7267)[0m     self.observations[self.pointer] = item.observation[32m [repeated 242x across cluster][0m
[36m(DataActor pid=7267)[0m ValueError: could not broadcast input array from shape (3,18) into shape (18,)[32m [repeated 242x across cluster][0m
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 466, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 400, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 466, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 400, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7a2460445a20>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 90, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 218, in teardown
    self._router.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Exception ignored in atexit callback: <function shutdown at 0x7a2483a65630>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 1986, in shutdown
    time.sleep(0.5)
KeyboardInterrupt:
