Ray cluster started. Available resources: {'node:172.23.48.184': 1.0, 'memory': 9546072884.0, 'GPU': 1.0, 'node:__internal_head__': 1.0, 'accelerator_type:G': 1.0, 'CPU': 12.0, 'object_store_memory': 4091174092.0}
Waiting for actors to initialize and run one episode...
[36m(LearnerActor pid=32997)[0m (Learner pid=32997) Initializing on GPU...
[36m(LearnerActor pid=32997)[0m (Learner pid=32997) Setup complete.

Warmup phase...
  Buffer size: 0/1000
[36m(DataActor pid=33001)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::ReplayBufferActor.add()[39m (pid=32998, ip=172.23.48.184, actor_id=5ff5e36a970de272378225be01000000, repr=<train.ReplayBufferActor object at 0x7c57787da650>)
[36m(DataActor pid=33001)[0m   File "/home/ryan/toy_mazero/train.py", line 46, in add
[36m(DataActor pid=33001)[0m     self.replay_buffer.add(item, priority)
[36m(DataActor pid=33001)[0m   File "/home/ryan/toy_mazero/utils/replay_buffer.py", line 128, in add
[36m(DataActor pid=33001)[0m     self.policy_targets[self.pointer] = item.policy_target
[36m(DataActor pid=33001)[0m ValueError: could not broadcast input array from shape (6,3,5) into shape (6,5)
[36m(DataActor pid=33001)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::ReplayBufferActor.add()[39m (pid=32998, ip=172.23.48.184, actor_id=5ff5e36a970de272378225be01000000, repr=<train.ReplayBufferActor object at 0x7c57787da650>)
[36m(DataActor pid=33001)[0m   File "/home/ryan/toy_mazero/train.py", line 46, in add
[36m(DataActor pid=33001)[0m     self.replay_buffer.add(item, priority)
[36m(DataActor pid=33001)[0m   File "/home/ryan/toy_mazero/utils/replay_buffer.py", line 128, in add
[36m(DataActor pid=33001)[0m     self.policy_targets[self.pointer] = item.policy_target
[36m(DataActor pid=33001)[0m ValueError: could not broadcast input array from shape (6,3,5) into shape (6,5)
[36m(DataActor pid=33001)[0m [32m2025-06-29 16:44:35[0m | [36mDEBUG[0m | [36mUpdating parameters from learner.[0m
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 467, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 401, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 467, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 401, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x77b488735a20>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 90, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 218, in teardown
    self._router.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Exception ignored in atexit callback: <function shutdown at 0x77b4aad09630>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 1986, in shutdown
    time.sleep(0.5)
KeyboardInterrupt:
